### ISSUE TITLE
Transit’s UUID should be IComparable to cljs.core/UUID and vice versa

### ISSUE THREAD

**Issue by tonsky** [cognitect/transit-cljs#11]

**Comment by swannodette** [comment]
fixed https://github.com/cognitect/transit-cljs/commit/e4ec6ab3a5b852034f4cad8f48fc394956f3a6c3

**Comment by tonsky** [comment]
The test is not testing UUID compare, it compares strings. Test should lose `pr-str` under `compare`

**Comment by swannodette** [comment]
Nice catch will fix

**Comment by swannodette** [comment]
After further review, this is blocked on the fact that `compare` is broken in ClojureScript wrt. to Clojure semantics http://dev.clojure.org/jira/browse/CLJS-1200

**Comment by swannodette** [comment]
fixed in transit-cljs 0.8.220 when combined with ClojureScript 0.0-3308
