### ISSUE TITLE
transit uuid conflicts with cljs uuid

### ISSUE THREAD

**Issue by yogthos** [cognitect/transit-cljs#13]
WARNING: uuid already refers to: cljs.core/uuid being replaced by: cognitect.transit/uuid at line 337 file:/Users/Yogthos/.m2/repository/com/cognitect/transit-cljs/0.8.215/transit-cljs-0.8.215.jar!/cognitect/transit.cljs

**Comment by swannodette** [comment]
fixed https://github.com/cognitect/transit-cljs/commit/2abd84bee3104dcce1d2efee801dbfbc038f3dc9

**Comment by yogthos** [comment]
:+1:
