### ISSUE TITLE
Publishing a changelog

### ISSUE THREAD

**Issue by danielcompton** [cognitect/transit-cljs#17]
It would be really helpful if this library published a changelog so I can see what has been changed, added, deprecated, e.t.c. when upgrading. For example 0.8.225 depends on a version of CLJS `1.7.107` that hasn't been marked stable yet, and may be using features introduced in that version.

**Comment by swannodette** [comment]
We may eventually publish a changelog, but it's not a priority. We use transit-cljs internally at Cognitect for various purposes and we may periodically cut releases for our own needs. Suffice to say there haven't been any real changes worth reporting to the world in a very a long time.
