### ISSUE TITLE
Ability to ignore tags when reading JSON?

### ISSUE THREAD

**Issue by sickill** [cognitect/transit-cljs#20]
I'm using transit-cljs because it's way faster than `JSON.parse + js->clj`. That's awesome.

I'm decoding user provided JSON files that happen to include `["~some stuff", ....]` and these get decoded as `[TaggedValue....]` which breaks stuff. Users include my `.js`, point it to a JSON file so I can't transit-encode them upfront. 

Is there a possibility to tell the `transit/reader` to stop treating tags in a special way?

**Comment by dchelimsky** [comment]
There is no API for that today, and it's really outside the objectives of the project. That said, the code is all here (and in transit-js) and you're free to extract the parts that make it a fast json reader for cljs (caching, etc).

**Comment by sickill** [comment]
Ok, thanks!

**Comment by dchelimsky** [comment]
If you do build something for this purpose, please feel free to let us know about it here on this thread. Maybe it'd help other folks who want the same thing. Cheers!

**Comment by sickill** [comment]
:+1:
