### ISSUE TITLE
API Docs public website contains no content

### ISSUE THREAD

**Issue by jdwaterson** [cognitect/transit-cljs#21]
Not sure if this is just a temporary blip or a symptom of some deeper problem, but the [API Docs] (http://cognitect.github.io/transit-cljs/) website for this repo, linked directly from the top of the home page, is currently showing no useful content for me. I get headers and top-level navigation but nothing else. Screen shot attached so you can see what I mean, in case you're seeing something different.

![screen shot 2015-10-20 at 17 46 26](https://cloud.githubusercontent.com/assets/2714395/10614536/c9212ec2-7752-11e5-9e6f-666871729686.png)

**Comment by puredanger** [comment]
codox has drifted a bit so I updated to the latest and refreshed the api docs

**Comment by jdwaterson** [comment]
Thanks Alex. Better service on Cognitect OSS than most commercial products. :-)
