### ISSUE TITLE
update Getting Started page

### ISSUE THREAD

**Issue by jiangts** [cognitect/transit-cljs#24]
Small thing: in the [getting started](https://github.com/cognitect/transit-cljs/wiki/Getting-Started) page,
```
(def w
  (t/writer :json-verbose
    {:handlers 
      {Point (PointHandler.)
       Size  (SizeHandler.)
       Rect  (RectHandler.)}})
```
a closing parenthesis is missing! Was copying and pasting into the repl and was wondering why the code wasn't returning...

**Comment by puredanger** [comment]
added, thx
