### ISSUE TITLE
Stabilized specification yet? Aching to start using transit for storage

### ISSUE THREAD

**Issue by vikeri** [cognitect/transit-cljs#29]
I have a React Native app that does quite a lot of serialization when I'm saving my state to localStorage, `pr-str` sometimes takes up to 100 ms which is not ideal. Thus I'm just wondering if the specification is stabilized yet so I could start using it for storage or if there are specification changes on the horizon?

**Comment by whilo** [comment]
Woud also be interested in this for indexedDB support in https://github.com/replikativ/konserve

**Comment by swannodette** [comment]
Nothing has changed in years and unlikely to.
