### ISSUE TITLE
Exclude uri?

### ISSUE THREAD

**Issue by mfikes** [cognitect/transit-cljs#39]
Much like #26, we could use an exclude for `uri?` because with https://github.com/clojure/clojurescript/commit/35ad08e6728d83d0e7e1cce1d724f080eb5abce4 we now get a `:redef` warning:

```
WARNING: uri? already refers to: cljs.core/uri? being replaced by: cognitect.transit/uri? at line 332 out/cognitect/transit.cljs
```

**Comment by olivergeorge** [comment]
Add a PR for this here because there doesn't seem to be a transit-cljs project here https://dev.clojure.org/jira/secure/BrowseProjects.jspa#all

**Comment by EmergentBehavior** [comment]
I'm seeing this too.

**Comment by thedavidmeister** [comment]
yeah me too, shows up in latest version of cljs which is needed to track latest hoplon version

**Comment by swannodette** [comment]
Fixed in master and cut a new release.
