### ISSUE TITLE
Bump transit-js dep in pom.xml to fix metadata encoding

### ISSUE THREAD

**Issue by mk** [cognitect/transit-cljs#46]
Trying to encode metadata in our project didn't work as expected, setting the `:transform` option just didn't have an effect. Tests are passing here because `project.clj` is using another version of transit than `pom.xml`.

https://github.com/cognitect/transit-cljs/blob/ada722e56f0dafd230ef3f5b4d2c1e6b09511c40/project.clj#L7

https://github.com/cognitect/transit-cljs/blob/ada722e56f0dafd230ef3f5b4d2c1e6b09511c40/pom.xml#L134-L136

As a workaround, adding a explicit require in `deps.edn` on the latest transit-js fixed the issue for me:
```clojure
com.cognitect/transit-js {:mvn/version "0.8.861"}
``` 

I'm happy to provide a PR for this one-line change in pom.xml it it helps.

**Comment by puredanger** [comment]
Done - I'll @swannodette do the release as needed.
