### ISSUE TITLE
fails to read BigInt tag?

### ISSUE THREAD

**Issue by spacegangster** [cognitect/transit-cljs#55]
When reading transit-clj encoded output like
`"[\"^ \",\"~:id\",\"~n61583\"]"` 
I'm getting `{:id #object[Transit$TaggedValue [TaggedValue: n 61583]]}`

I would like to have that as a plain JS Integer.
Not critical at all, my current workaround is that I cast BigInt to Long on Clojure side.

Transit cljs version
`[com.cognitect/transit-cljs  "0.8.256"]`

Transit clj version
`[com.cognitect/transit-clj "1.0.324"]`

Cheers!

**Comment by swannodette** [comment]
@spacegangster thanks for the report, the README was just wrong, in JS we don't have a Big Decimal or Big Integer type available. These default to tagged values.
