### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by lackita** [cognitect/transit-cljs#6]
When I run "lein cljsbuild once" I get the following errors:

    WARNING: No such namespace: com.cognitect.transit.eq at line 15 file:/Users/cwilliams/.m2/repository/com/cognitect/transit-cljs/0.8.199/transit-cljs-0.8.199.jar!/cognitect/transit.cljs
    WARNING: No such namespace: com.cognitect.transit.types at line 15 file:/Users/cwilliams/.m2/repository/com/cognitect/transit-cljs/0.8.199/transit-cljs-0.8.199.jar!/cognitect/transit.cljs
    WARNING: No such namespace: com.cognitect.transit at line 15 file:/Users/cwilliams/.m2/repository/com/cognitect/transit-cljs/0.8.199/transit-cljs-0.8.199.jar!/cognitect/transit.cljs

Then when I try to load the compiled file, I get this error:

    [Error] goog.require could not find: com.cognitect.transit.eq
	require (sheet.js, line 108)
	global code (sheet.js, line 28738)
    [Error] Error: goog.require could not find: com.cognitect.transit.eq
	require (sheet.js, line 110)
	global code (sheet.js, line 28738)

A couple of details that might be relevant:
* I'm using version 0.8.199
* It's being imported into my namespace using cljs-ajax

**Comment by swannodette** [comment]
What version of ClojureScript are you attempting to use?

**Comment by lackita** [comment]
0.0-2173

**Comment by swannodette** [comment]
@lackita that's a pretty old version of compiler I don't think Google Closure JavaScript libraries can be loaded off the classpath. The project specifies 0.0-2371 as a minimum.

**Comment by lackita** [comment]
Thanks, I guess I accidentally specified an old version.
