### ISSUE TITLE
project.clj version and tag mismatch

### ISSUE THREAD

**Issue by johnbendi** [cognitect/transit-cljs#8]
Why is there a tag for v0.8.207 and yet project.clj has 0.8.202 as current version?

**Comment by johnbendi** [comment]
This is also the issue with transit-js. Perhaps I'm missing something?

**Comment by puredanger** [comment]
Without looking at it, that sounds like it could be an issue with the order of events in the release script. I can take a look at this tomorrow.

**Comment by johnbendi** [comment]
This issue persists. The tag is at v0.8.220 yet project.clj has v0.8.202. This doesn't help wiht lein install. Please so something about this.

**Comment by swannodette** [comment]
@johnbendi this isn't a high priority issue as we don't rely much on Leiningen in this project. We use Maven. If you really need a local install try `build/package_local`.
