### ISSUE TITLE
transit.cljs:285 (ty/integer s) undefined

### ISSUE THREAD

**Issue by gberenfield** [cognitect/transit-cljs#9]
Seeing this in my console trying to use `(cognitect.transit/integer "30")`
Looking in my js output directory, it seems like it's missing from `com/cognitect/transit/types.js`

Using transit-cljs version "0.8.207"

**Comment by swannodette** [comment]
fixed https://github.com/cognitect/transit-cljs/commit/80c9af9a6d34e440d96b9be43bf1f945d8c15a4a
